openapi: "3.0.2"
info:
  title: E-Comerce SCARPA
  description: Open API scarpa
  version: "1.0"
servers:
  - url: 3.83.173.201

tags:
  - name: Autentication
  - name: Users
  - name: Product
  - name: Cart
  - name: Order

paths:
  /login:
    post:
      tags:
        - Autentication
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#"
            example:
              name: altera@gmail.com
              password: qwerty123
      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseLoginSuccess"
              examples:
                responseData1:
                  description: response success 1
                  value:
                    {
                      code: 200,
                      status: "success",
                      message: "Login Success",
                      data:
                        {
                          id: 1,
                          nama: "Sutiaji",
                          token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MzgzMjYxODAsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.AebFR-oQjUSOMez2ucDWkiMrS2eQIPmcYm5c71qZ_co",
                        },
                    }
        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Login Failed. Email or Password incorrect.",
                    }
                responseData2:
                  description: response failed 2
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Login Failed. Your email doesn't match any entry",
                    }

  /users:
    post:
      tags:
        - Users
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#"
            example:
              name: sutiaji
              email: altera@gmail.com
              password: qwerty123
      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#"
              examples:
                response data:
                  description: response success 1
                  value:
                    {
                      code: 200,
                      status: "success",
                      message: "success operation create data",
                    }
        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Login Failed. Email or Password incorrect.",
                    }
                responseData2:
                  description: response failed 2
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Login Failed. Your email doesn't match any entry",
                    }
  /users/{id}:
    get:
      tags:
        - Users
      parameters:
        - name: iduser
          description: get data by id
          in: query
          schema:
            type: integer
            example: 1
          required: true
      responses:
        "403":
          description: forbiden
        "404":
          description: No data
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#"
              examples:
                response data:
                  description: response success 1
                  value: { id: 1, name: "sutiaji", email: "sutiaji@gmail.com" }
        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value:
                    {
                      code: 400,
                      status: "login failed",
                      message: "Login Failed. Email or Password incorrect.",
                    }
                responseData2:
                  description: response failed 2
                  value:
                    {
                      code: 400,
                      status: "failed",
                      message: "Login Failed. Your email doesn't match any entry",
                    }
    put:
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#"
            example:
              name: sutiaji
              email: altera@gmail.com
              password: qwerty123
      parameters:
        - name: iduser
          in: query
          schema:
            type: integer
            example: 1
          required: true
      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#"
              examples:
                response data:
                  value:
                    code: 200
                    status: "success"
                    message: "Successful Operation"

        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value: { code: 400, status: "failed", message: "Bad Request" }
    delete:
      tags:
        - Users
      parameters:
        - name: iduser
          in: query
          schema:
            type: integer
            example: 1
          required: true
      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#"
              examples:
                response data:
                  value:
                    code: 200
                    status: "success"
                    message: "Successful Operation"

        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value: { code: 400, status: "failed", message: "Bad Request" }

  /products:
    post:
      tags:
        - Product
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#"
            example:
              id: 5
              name: adidas1
              price: 500000
              qty: 1
              description: ini sepetu runing adidas1

      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#"
              examples:
                response data:
                  description: response success 1
                  value:
                    {
                      code: 200,
                      status: "success",
                      message: "success operation create data",
                    }
        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value: { code: 400, status: "failed", message: "Bad request" }

  /cart:
    post:
      tags:
        - Cart
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#"
            example:
              product_id: 5
              qty: 1

      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#"
              examples:
                response data:
                  description: response success 1
                  value:
                    {
                      code: 200,
                      status: "success",
                      message: "success operation create data",
                    }
        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value: { code: 400, status: "failed", message: "Bad request" }

  /order:
    post:
      tags:
        - Order
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#"
            example:
              cart_id: [2]
              addres:
      responses:
        "200":
          description: Success Response
          content:
            application/json:
              schema:
                $ref: "#"
              examples:
                response data:
                  description: response success 1
                  value:
                    {
                      code: 200,
                      status: "success",
                      message: "success operation create data",
                    }
        "400":
          description: Failed Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/failedResponse"
              examples:
                responseData1:
                  description: response failed 1
                  value: { code: 400, status: "failed", message: "Bad request" }

components:
  schemas:
    requestLogin:
      type: object
      properties:
        "email":
          type: string
          minLength: 1
        "password":
          type: string
          minLength: 1
    responseLoginSuccess:
      type: object
      properties:
        {
          "code": { type: number },
          "message": { type: string },
          "status": { type: string },
          "data": { type: object },
        }
    failedResponse:
      type: object
      properties:
        {
          "code": { type: number },
          "message": { type: string },
          "status": { type: string },
        }
